### ISSUE TITLE
在windows下生成可执行文件后，打开出错

### ISSUE THREAD

**Issue by amoviolin** [shuoGG1239/TcpUdpSerialPortTool#5]
提示failed to execute script main

**Comment by amoviolin** [comment]
经检查是找不到json文件。错误信息如下:
Traceback (most recent call last):
  File "TcpUdpSerialPortTool-master\main.py", line 26, in <module>
  File "TcpUdpSerialPortTool-master\main.py", line 11, in run_with_titlebar
  File "site-packages\QCandyUi\CandyWindow.py", line 37, in on_call
  File "TcpUdpSerialPortTool-master\TcpUdpSerialportTool.py", line 74, in __init
__
  File "TcpUdpSerialPortTool-master\util\ConfigFile.py", line 10, in __init__
FileNotFoundError: [Errno 2] No such file or directory: 'condat.json'
[11376] Failed to execute script main
